exercism/nim

.travis.yml
_test/check_exercises.nim
bob/example.nim
word-count/example.nim
word-count/word_count_test.nim

Nimrod was renamed nim and has gained some versions. The existing exercises didn't require any fixes luckily.

Update to new nim

---

.travis.yml
react/example.nim
word-count/example.nim
word-count/word_count_test.nim

Requires a change to the build environment (need glibc >= 2.17) and a few tweaks to the examples

Update to Nim v0.14.2

---

binary/binary_test.nim
binary/example.nim
config.json

Raises an exception to account for bad input.

Adds "binary" exercise

---

react/react_test.nim

This is important because the README specifies that callbacks are called
"when the cell's value in a new stable state **has changed** from the
previous stable state."
The example solution already passes this test, so no change to the
example solution is necessary.
However, there is a type of solution that will not pass this test, so
this test is indeed still useful:
This is the type of solution that, when a cell gets updated, marks it
dirty, and then afterwards calls the callbacks of all dirty cells.
This test shows that a dirty bit is not enough information; you need to
store the last stable value of the cell so that you can compare it
against the new stable value.

react: Add test for dependencies changing but value not changing

---

README.md

Change name to Nim and fix Travis image link

---

README.md

a step in fixing https://github.com/exercism/exercism.io/issues/3112.

move attribution here from exercism.io/ATTRIBUTION.md

---

docs/INSTALLATION.md
docs/RESOURCES.md
docs/TESTS.md

Some quick documentation to help people get started with Nim

Adds docs for installing and testing

---

config.json
exercises/scrabble-score/README.md
exercises/scrabble-score/example.nim
exercises/scrabble-score/scrabble_score_test.nim

Due to using `toLowerAscii` this code needs Nim 1.8.0, which will be upgraded with PR #56 
Please point out anyway of making this code better or more idiomatic. Thanks!

Adds scrabble-score exercise

---

config.json
exercises/roman-numerals/README.md
exercises/roman-numerals/example.nim
exercises/roman-numerals/roman_numerals_test.nim

Hi, 
As I'm still learning Nim please point out anyways of making this better. I want to make sure that this is idiomatic Nim. 
Thanks!

Adds roman-numerals exercise

---

config.json
exercises/pangram/README.md
exercises/pangram/example.nim
exercises/pangram/pangram_test.nim

This PR needs Nim 1.8.0 to be installed on Travis CI, which is upgraded in PR #56 
Feel free to point out anyway to make this better! Thanks!

Adds pangram exercise

---

.gitignore
config.json
exercises/gigasecond/README.md
exercises/gigasecond/example.nim
exercises/gigasecond/gigasecond_test.nim

Adds gigasecond exercise

---

exercises/bob/README.md
exercises/bob/bob_test.nim
exercises/bob/example.nim

Updates to the bob exercise for issue #55

Update for bob exercise

---

exercises/space-age/example.nim
exercises/space-age/space_age_test.nim

After some thinking about this exercise and taking a good look at the problem specifications I feel this is a better match. It also removes the need to create a type just to hold `seconds`

Updates to space-age exercise

---

docs/ABOUT.md

I noticed that we still needed some about text for Nim, I'm not the best writer in the world but here is my take on it. Wouldn't mind a review to make sure I'm representing Nim correctly.

Adds about text for Nim

---

exercises/leap/leap_test.nim

Update based on specs found at https://github.com/exercism/problem-specifications/blob/master/exercises/leap/canonical-data.json

Updates to leap exercise

---

exercises/word-count/HINT.md
exercises/word-count/example.nim
exercises/word-count/word_count_test.nim

Based on issue #77, I have rewrote the word-count exercise to match updates to the problem-specifications. I also have added a Hint file to help people with the return type and info about Nim's table module.

Update for word-count exercise

---

exercises/allergies/allergies_test.nim
exercises/allergies/example.nim
exercises/difference-of-squares/difference_of_squares_test.nim
exercises/difference-of-squares/example.nim
exercises/gigasecond/example.nim
exercises/gigasecond/gigasecond_test.nim
exercises/nucleotide-count/example.nim
exercises/nucleotide-count/nucleotide_count_test.nim
exercises/pangram/example.nim
exercises/pangram/pangram_test.nim
exercises/triangle/example.nim
exercises/triangle/triangle_test.nim

I know this is a personal preference, but for Nim it's recommended to use camelCase: https://nim-lang.org/docs/nep1.html
And also - any code which uses snake_case will NOT break because Nim is partially style insensitive

Use camelCase instead of snake_case

---

config.json

This should help deal with issues #83 and put ll the exercises in a better order for someone new to Nim, also add some missing details for topics.

Update exercises order and details

---

exercises/allergies/allergies_test.nim
exercises/anagram/anagram_test.nim
exercises/binary/binary_test.nim
exercises/bob/bob_test.nim
exercises/bracket-push/bracket_push_test.nim
exercises/difference-of-squares/difference_of_squares_test.nim
exercises/gigasecond/example.nim
exercises/gigasecond/gigasecond_test.nim
exercises/hamming/hamming_test.nim
exercises/hello-world/helloworld_test.nim
exercises/leap/example.nim
exercises/nucleotide-count/nucleotide_count_test.nim
exercises/pangram/example.nim
exercises/pangram/pangram_test.nim
exercises/raindrops/raindrops_test.nim
exercises/rna-transcription/rna_transcription_test.nim
exercises/roman-numerals/example.nim
exercises/roman-numerals/roman_numerals_test.nim
exercises/scrabble-score/example.nim
exercises/scrabble-score/scrabble_score_test.nim
exercises/triangle/example.nim
exercises/triangle/triangle_test.nim

Clean up of some test and fix spacing to be 2

Clean up of tests and formatting

---

docs/SNIPPET.txt

To help with #86, small update to the snippet to make to output something if someone was to copy it and run it locally.
This will update this area of the v2 site, at https://v2.exercism.io/tracks/nim

Small update to Snippet

---

docs/LEARNING.md

I think this is the last needed doc for #34

Adds Learning Doc

---

config.json
exercises/nth-prime/README.md
exercises/nth-prime/example.nim
exercises/nth-prime/nth_prime_test.nim

I feel like this can be cleaned up a bit, if anyone has any suggestions please share! :)

Adds nth-prime exercise

---

exercises/difference-of-squares/README.md
exercises/leap/README.md

Update READMEs: difference-of-squares, leap

---

exercises/pangram/pangram_test.nim

pangram: Update tests to 1.4.1

---

exercises/gigasecond/gigasecond_test.nim

Upstream: https://github.com/exercism/problem-specifications/commit/2e1c5ac35fa702870b9a6c717cab218446c96497

gigasecond: Update tests to 2.0.0

---

config.json
exercises/grains/README.md
exercises/grains/example.nim
exercises/grains/grains_test.nim

This PR is to add a new exercise for `grains`, [here is a link to the problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/grains)

Adds grains exercise

---

exercises/word-count/README.md

To complete https://github.com/exercism/nim/pull/150.

word-count: Update README with revised hint

---

config.json
exercises/secret-handshake/README.md
exercises/secret-handshake/example.nim
exercises/secret-handshake/secret_handshake_test.nim

Hi, this PR is to add a new exercise for `secret-handshake`, [here is a link to the problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/secret-handshake)
Thanks!

Adds secret-handshake exercise

---

config.json
exercises/matrix/README.md
exercises/matrix/example.nim
exercises/matrix/matrix_test.nim

[Exercise description](https://github.com/exercism/problem-specifications/blob/master/exercises/matrix/description.md)
[Canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/matrix/canonical-data.json)
This exercise is intended partly as a basic introduction to nested datatypes. Therefore the `col` and `row` procedures return a `seq` (no `array` or `static[int]`), and the example solution uses a simple `seq[seq[int]]` implementation.
We can consider adding a `hints.md` file to an exercise of topic `matrices` - similar to [the hint for rust/saddle-points](https://github.com/exercism/rust/blob/master/exercises/saddle-points/.meta/hints.md), and suggest that people interested in multidimensional arrays in Nim should look at:
- …

Implement exercise: matrix

---

config.json
exercises/prime-factors/README.md
exercises/prime-factors/example.nim
exercises/prime-factors/prime_factors_test.nim

[Exercise description](https://github.com/exercism/problem-specifications/blob/master/exercises/prime-factors/description.md)
[Canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/prime-factors/canonical-data.json)
The example solution uses a parameter of type `int64`.

Implement exercise: prime-factors

---

config.json
exercises/rotational-cipher/README.md
exercises/rotational-cipher/example.nim
exercises/rotational-cipher/rotational_cipher_test.nim

[Exercise description](https://github.com/exercism/problem-specifications/blob/master/exercises/rotational-cipher/description.md)
[Canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/rotational-cipher/canonical-data.json)
The `canonical-data` does not require decryption, or rotation by a negative number.
And as usual, unicode support isn't required.

Implement exercise: rotational-cipher

---

config.json
exercises/series/README.md
exercises/series/example.nim
exercises/series/series_test.nim

[Exercise description](https://github.com/exercism/problem-specifications/blob/master/exercises/series/description.md)
[Canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/series/canonical-data.json)
A fairly straightforward exercise - not much to say.
This exercise could be placed quite early in the track.

Implement exercise: series

---

config.json
exercises/clock/README.md
exercises/clock/clock_test.nim
exercises/clock/example.nim

[Exercise description](https://github.com/exercism/problem-specifications/blob/master/exercises/clock/description.md)
[Canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/clock/canonical-data.json)
Many tracks (e.g. Python, Go, Rust, F#, C#, Ruby) use `clock` as a `core` exercise. There might be better choices for the Nim track.

Implement exercise: clock

---

exercises/armstrong-numbers/armstrong_numbers_test.nim

Update armstrong-numbers to v1.1.0 based on the new test case in [canonical-data.json](https://github.com/exercism/problem-specifications/blob/master/exercises/armstrong-numbers/canonical-data.json) from

Updates to armstrong-numbers for v1.1.0

---

config.json
exercises/saddle-points/README.md
exercises/saddle-points/example.nim
exercises/saddle-points/saddle_points_test.nim

[Exercise description](https://github.com/exercism/problem-specifications/blob/master/exercises/saddle-points/description.md)
[Canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/saddle-points/canonical-data.json)
- This exercise should be placed after `matrix`.
- There is no test involving irregular matrices.
I implement the input type as `seq[seq[int]]`. A more efficient way to implement a `M×N` matrix is something like
```Nim
type
Matrix[A] = ref object
M, N: int
data: seq[A]
```
or to use `neo`, but both are beyond the scope of this exercise.
We can consider adding a `hints.md` file to an exercise of topic `matrices`, similar to [the hint for rust/saddle-points](https://github.com/exercism/rust/blob/master/exercises/saddle-points/.meta/hints.md), …

Implement exercise: saddle-points

---

.travis.yml

See https://nim-lang.org/blog/2019/05/13/version-0196-released.html

Travis: Update to use Nim 0.19.6

---

.travis.yml
bin/travis-install.sh

This PR consists of 9 atomic commits that overhaul the Travis CI setup.
Each commit passes CI. The last two commits have been built here to demonstrate correctness.
Many of these commits could have had their own PRs. Therefore, to preserve clarity of the commit messages, please **do not squash**.
Summary:
- Prepare for future work.
- Allow more testing options.
- Build faster.
- Fail faster.
- Be stricter.
- Make build logs cleaner and more useful.
See the commit messages for details.
I'll make some changes due to Nim 0.20.0 being released.
Now ready for review.
Changes made due to 0.20.0:
- Removed the last few commits, which significantly changed the build process.
- Added a commit to use the pre-built binaries instead. As a new feature for 0.20.0, Nim now provides them for Linux.
The …

Travis overhaul

---

.travis.yml

See https://nim-lang.org/blog/2019/07/17/version-0202-released.html
(I haven't forgotten about my existing PRs. More progress is "coming soon".)

Travis: Use Nim 0.20.2

---

exercises/word-count/word_count_test.nim

See https://github.com/exercism/problem-specifications/commit/055a260854943e612ce4d828a6dc4ec88b4682b5

word-count: Update tests to 1.4.0

---

exercises/raindrops/README.md

See https://github.com/exercism/problem-specifications/commit/477010debf3db1a1c56b993a554ea38dc65cd0ad

README(raindrops): Simplify description

---

exercises/etl/README.md
exercises/etl/etl_test.nim
exercises/leap/leap_test.nim
exercises/matrix/matrix_test.nim
exercises/resistor-color-duo/README.md
exercises/resistor-color-duo/example.nim
exercises/resistor-color-duo/resistor_color_duo_test.nim
exercises/scrabble-score/README.md
exercises/space-age/README.md

This PR brings the track up-to-date by updating tests and READMEs.
The commits are ordered by date of upstream change. See the commit messages for further details.

Update tests and READMEs

---

.travis.yml

See https://nim-lang.org/blog/2019/09/23/version-100-released.html

CI(Travis): Use Nim 1.0.0

---

exercises/hello-world/hello_world.nim

This PR adds a stub file to every implemented exercise. This is possible now that `check_exercises.nim` supports stubs (see #200).
I propose we start simple: let's just add an empty stub file to every exercise except `hello-world` (which gets a special one). This solves the main problem of users having to create a file. We can still consider later adding to some stubs, especially those for early or `core` exercises.
However, I think we shouldn't add many function signatures - it would rob users of useful practice, especially as Nim has a concise syntax.
The `hello-world` exercise should be as simple as possible. I looked through the other tracks and liked the Rust track's stub, so I stole the idea.
This small stub already hints at many useful points, such as:
- The correct way to write a …

Feature: Add stub files

---

exercises/robot-name/README.md

This PR brings all the exercise READMEs up-to-date.
Upstream:
- https://github.com/exercism/problem-specifications/commit/81c1eaa

README(robot-name): Use singular "robot"

---

exercises/grade-school/.meta/hints.md
exercises/grade-school/README.md
exercises/isbn-verifier/README.md
exercises/word-count/.meta/hints.md
exercises/word-count/README.md

This small PR causes `configlet generate` to again make no changes when run.
See the commit messages for more details.

READMEs: Improve style of hints; Run `configlet generate`

---

.travis.yml
bin/travis-install.sh

This PR tweaks the Travis CI configuration slightly.
It also makes the install script a little more robust and easier to extend.
See the commit messages for more details.

CI(Travis): Update to 18.04 Bionic; Set language to `minimal`; Small tweaks

---

exercises/grade-school/README.md
exercises/grade-school/grade_school_test.nim

Upstream:
- https://github.com/exercism/problem-specifications/commit/2ee5596

README(grade-school): Clarify "whole roster" query

---

exercises/two-fer/README.md

This PR causes `configlet generate` to again make no changes when run.
Upstream:
https://github.com/exercism/problem-specifications/commit/63bb34c

README(two-fer): Remove trailing whitespace

---

_test/check_exercises.nim

CI(check_exercises): Move imports below doc comment

---

exercises/bob/bob_test.nim

Upstream: https://github.com/exercism/problem-specifications/commit/1904e91

Test(bob): 1.5.0 (#231)

---

exercises/bob/bob_test.nim

Upstream: https://github.com/exercism/problem-specifications/commit/42b9d45

Test(bob): 1.6.0 (#232)

---

exercises/luhn/luhn_test.nim

Upstream: https://github.com/exercism/problem-specifications/commit/498d10f

Test(luhn): 1.7.0

---

exercises/scale-generator/README.md

Upstream: https://github.com/exercism/problem-specifications/commit/9bfee5f

README(scale-generator): Fix name of augmented interval

---

exercises/resistor-color/README.md

Upstream: https://github.com/exercism/problem-specifications/commit/5b65046

README(resistor-color): Add exercise requirements

---

exercises/two-fer/README.md

Upstream: https://github.com/exercism/problem-specifications/commit/5f14f2e

README(two-fer): Replace "X" with "name"

---

exercises/luhn/README.md

Upstream: https://github.com/exercism/problem-specifications/commit/9664fc7

README(luhn): Change the digits used in examples

---

exercises/robot-name/README.md

Upstream: https://github.com/exercism/problem-specifications/commit/3f1d2a2

README(robot-name): Remove dead link

---

exercises/diamond/diamond_test.nim
exercises/hello-world/hello_world_test.nim
exercises/raindrops/raindrops_test.nim

This small PR reduces the diff between the canonical data and the implemented tests.

Refactor: Sync some test names with upstream

---

exercises/largest-series-product/largest_series_product_test.nim

Just to be more consistent with the other test names in this file.

Refactor(largest-series-product): Rename the bonus test

---

exercises/resistor-color-duo/README.md
exercises/resistor-color/README.md

This PR also changes `resistor-color-duo`.
Upstream: https://github.com/exercism/problem-specifications/commit/c693bbc0517c

README(resistor-color): Extend explanation

---

exercises/nucleotide-count/README.md

Upstream: https://github.com/exercism/problem-specifications/commit/53df31f552ce

README(nucleotide-count): Improve explanation

---

exercises/leap/.meta/tests.toml
exercises/leap/test_leap.nim

Upstream: https://github.com/exercism/problem-specifications/commit/a2c75d2e71c6

Test(leap): Fix typo

---

exercises/practice/hello-world/hello_world.nim

Simplify the `hello-world` exercise's stub. The goal of this is to make things easier for students to get started and to introduce as little syntax as possible.
See https://github.com/exercism/v3-launch/issues/46

🤖 Simplify `hello-world` stub

---

.github/labels.yml
CODE_OF_CONDUCT.md

This PR is just #318 with the merge conflict resolved. I can't resolve the conflict on that PR due to its settings.

add Code of Conduct

---

exercises/practice/acronym/.meta/config.json
exercises/practice/armstrong-numbers/.meta/config.json
exercises/practice/binary/.meta/config.json
exercises/practice/collatz-conjecture/.meta/config.json
exercises/practice/darts/.meta/config.json
exercises/practice/grade-school/.meta/config.json
exercises/practice/hello-world/.meta/config.json
exercises/practice/high-scores/.meta/config.json
exercises/practice/resistor-color/.meta/config.json
exercises/practice/reverse-string/.meta/config.json
exercises/practice/scale-generator/.meta/config.json
exercises/practice/twelve-days/.meta/config.json
exercises/practice/two-fer/.meta/config.json
exercises/practice/yacht/.meta/config.json

This commit is the result of running:
```
configlet sync -uy --metadata
```

exercises(practice): sync metadata for 14 exercises

---

_test/check_exercises.nim

A small refactoring and some superficial improvements.

check_exercises: tidy up

---

exercises/practice/pangram/.meta/example.nim

This change results in a speed up of about 3-4x on my machine
Review on the commit message is greatly appreciated

Refactor(pangram): remove unnecessary string operations in `example.nim`

---

exercises/practice/acronym/.docs/instructions.md
exercises/practice/anagram/.docs/instructions.md
exercises/practice/diffie-hellman/.docs/instructions.md
exercises/practice/isbn-verifier/.docs/instructions.md
exercises/practice/pangram/.docs/instructions.md
exercises/practice/saddle-points/.docs/instructions.md
exercises/practice/scale-generator/.docs/instructions.md

This commit is the result of running:
```shell
configlet sync -uy --docs
```
The corresponding upstream state: https://github.com/exercism/problem-specifications/commit/0eda2318cb56

exercises(practice): sync docs for 7 exercises
