exercism/nim

config/exercise_readme.go.tmpl, exercises/anagram/README.md, exercises/binary/README.md, exercises/bob/README.md, exercises/difference-of-squares/README.md, exercises/hamming/README.md, exercises/hello-world/README.md, exercises/leap/README.md, exercises/nucleotide-count/README.md, exercises/queen-attack/README.md, exercises/raindrops/README.md, exercises/react/README.md, exercises/rna-transcription/README.md, exercises/triangle/README.md, exercises/word-count/README.md
We are working towards making exercises stand-alone. That is to say: no more generating READMEs on the fly.
This will give maintainers more control over each individual exercise README, and it will also make some of the backend logic for delivering exercises simpler.
The README template uses the Go text/template package, and the default templates generate the same READMEs as we have been generating on the fly.  See the documentation in [regenerating exercise readmes][regenerate-docs] for details.
The READMEs can be generated at any time using a new 'generate' command in configlet. This command has not yet landed in master or been released, but can be built from source in the generate-readmes branch on [configlet][].
[configlet]: https://github.com/exercism/configlet
[regenerate-docs]: …
=> Generate static exercise README templates

.travis.yml, exercises/anagram/example.nim, exercises/word-count/example.nim
Updates `.travis.yml` to build with Nim v0.18.0 and fixes `toLower is deprecated` warnings
=> Upgrade Travis CI to use Nim v0.18.0

exercises/triangle/example.nim, exercises/triangle/triangle_test.nim
From looking at issue #50, I found that our test for triangle exercise didn't match what was in the [problem specifications](https://github.com/exercism/problem-specifications/blob/master/exercises/triangle/canonical-data.json) for this exercise. I have updated the tests and the code to match.
Not sure how we roll out updates for exercises that people may have done already, this would make people's solutions invalid.
=> Updates to triangle exercise

config.json
For issue #86 to help with V2 launch, this adds a `blurb` to the `config.json` that will show up on the https://v2.exercism.io/tracks/nim in places of the `TODO`
=> Adds blurb to config.json

config.json
I think after #98 (Updates to all the `README.md`) is merged, we are all set to turn `active` to `true` for the Nim track. This will close out the #13 (Launch planning). If there is something missing or something else that needs to happen let me know and I'll work on adding them to the track before merging this.
=> Set active to true for Nim Track

.travis.yml
14.04 Trusty reaches End-of-Life in April 2019.
(18.04 Bionic is not yet available on Travis).
=> Travis CI: Update to 16.04 Xenial

exercises/acronym/acronym_test.nim, exercises/acronym/example.nim
`isAlphaAscii(s: string)` is deprecated in Nim 0.20, and the warning is shown in Nim 0.19. Note that `isAlphaAscii(c: char)` is not deprecated.
Reference: https://github.com/nim-lang/Nim/commit/7f81519f4114dbb49fcd68ca2361920bf374fb1c
If these pull requests are acceptable, I'd prefer if they were merged `fast-forward` if possible (that is, without an extra merge commit for each). Thanks.
=> acronym: Update tests and example to 1.7.0, and fix warning

exercises/word-count/.meta/hints.md, exercises/word-count/word_count_test.nim
The use of `TableRef` seems like an implementation detail, especially given that one idiomatic solution uses a `CountTable`.
Instead, allow any data structure where the `` `[]` `` operator returns an `int`. For example, it is possible to use the previously-required `critbits` module (if the extra import is added to the test file).
I left `TableRef` in `hints.md` so that the student is still introduced to ref and value semantics in Nim.
=> word-count: Update tests to 1.3.0, and don't hardcode TableRef

exercises/space-age/example.nim, exercises/space-age/space_age_test.nim
Float comparison should be performed without rounding, and `round(x: float, places: int)` is deprecated in Nim 0.19. Note that `round(x: float)` is not deprecated.
Nim reference: https://github.com/nim-lang/Nim/commit/5076fda2e25a7f14dac130b591de6cc1eebfcc06
Upstream: https://github.com/exercism/problem-specifications/pull/1441
The numbers were changed to fit within a 32-bit int range.
=> space-age: Update tests to 1.2.0, and fix warning

config.json, exercises/all-your-base/README.md, exercises/all-your-base/all_your_base_test.nim, exercises/all-your-base/example.nim
Reference:
[exercism/problem-specifications/exercises/all-your-base](https://github.com/exercism/problem-specifications/tree/master/exercises/all-your-base)
Implementation details:
Similar to other tracks (e.g. Haskell and Rust), the function's arguments are ordered differently than in the canonical data. The new order is more idiomatic Nim, and it allows clean use of Nim's method call syntax: `[1, 0, 1].convert(2, 10)`.
I don't have strong opinions about using `array` rather than `seq` for the input digits, but this could be an opportunity for Nim students to practise using `openArray`.
Deprecation:
The `all-your-base` exercise replaces the `binary` exercise, which [will be officially deprecated soon](https://github.com/exercism/problem-specifications/issues/279).
=> all-your-base: Add exercise, and deprecate binary

config.json, exercises/darts/README.md, exercises/darts/darts_test.nim, exercises/darts/example.nim
[Exercise description](https://github.com/exercism/problem-specifications/blob/master/exercises/darts/description.md)
[Canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/darts/canonical-data.json)
I'll set the other PRs to the new "draft" mode until I have time to comment on any implementation details in the PR description.
For simplicity, in `config.json` I added all new exercises after `react`, and set `unlocked_by` to `null`. So for now, I suggest merging the new exercises into `config.json` below `react` and around `secret-handshake`, in alphabetical order.
Alphabetical order could also help reduce the diff noise later if [this suggested config.json ordering](https://github.com/exercism/configlet/issues/152#issuecomment-449981969) becomes the …
=> Implement exercise: darts

exercises/leap/leap_test.nim
Updates `leap` to version 1.5.0, https://github.com/exercism/problem-specifications/pull/1465
=> leap: Update tests to 1.5.0

config.json, exercises/etl/README.md, exercises/etl/etl_test.nim, exercises/etl/example.nim
[Exercise description](https://github.com/exercism/problem-specifications/blob/master/exercises/etl/description.md)
[Canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/etl/canonical-data.json)
The tests are verbose so that the user's solution can return any hash table type (`Table`, `OrderedTable`, `CountTable`, `TableRef`, `OrderedTableRef`, `CountTableRef`).
I think this way is the most clear to a student. If we change the approach, then we should also change it for other exercises that use `tables`.
There is currently a `hints.md` file for `word-count`. When we restructure the track, we should move this hint to the easiest exercise that uses `tables`.
1. Require that the solution uses an arbitrary hash table type, e.g. `Table`:
```Nim
test …
```
=> Implement exercise: etl

config.json, exercises/high-scores/README.md, exercises/high-scores/example.nim, exercises/high-scores/high_scores_test.nim
[Exercise description](https://github.com/exercism/problem-specifications/blob/master/exercises/high-scores/description.md)
[Canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/high-scores/canonical-data.json)
The input is implemented as `seq`, not `array`. Nim students should know about `openArray`, but let's not insist on it for this exercise.
In Nim 0.19.4, `sort` and `sorted` require the `cmp` parameter. It [won't be needed](https://nim-lang.github.io/Nim/algorithm.html#sorted,openArray[T]) in Nim 0.20.
Other tracks use `high-scores` as a `core` exercise to introduce classes. But there are more appropriate exercises for introducing `object`, `type` or `tuple` in Nim.
Our approach should more similar to that of, for example, [the F# …
=> Implement exercise: high-scores

config.json, exercises/isbn-verifier/README.md, exercises/isbn-verifier/example.nim, exercises/isbn-verifier/isbn_verifier_test.nim
[Exercise description](https://github.com/exercism/problem-specifications/blob/master/exercises/isbn-verifier/description.md)
[Canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/isbn-verifier/canonical-data.json)
The example solution illustrates a fast, imperative approach that uses only one loop over the input. Other common approaches might use regular expressions, `strutils.replace`, or `sequtils`.
For clarity, let's keep using the style
- `check a == true`
- `check b == false`
rather than the equivalent
- `check a`
- `check not b`
=> Implement exercise: isbn-verifier

config.json, exercises/kindergarten-garden/README.md, exercises/kindergarten-garden/example.nim, exercises/kindergarten-garden/kindergarten_garden_test.nim
[Exercise description](https://github.com/exercism/problem-specifications/blob/master/exercises/kindergarten-garden/description.md)
[Canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/kindergarten-garden/canonical-data.json)
The return type is implemented as a `seq`. Returning `array` for this exercise feels somewhat like "overfitting", but that will also pass the tests. That is, `[1, 2] == @[1, 2]` is [true](https://nim-lang.github.io/Nim/system.html#%3D%3D%2CopenArray%5BT%5D%2CopenArray%5BT%5D).
I define `smallGarden` and `fullGarden` for the tests with common input, and for now only use one `suite`. But it's debatable; maybe some track-wide convention for using multiple `suite` statements will become more obvious later. I think it feels a bit …
=> Implement exercise: kindergarten-garden

config.json, exercises/largest-series-product/README.md, exercises/largest-series-product/example.nim, exercises/largest-series-product/largest_series_product_test.nim
[Exercise description](https://github.com/exercism/problem-specifications/blob/master/exercises/largest-series-product/description.md)
[Canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/largest-series-product/canonical-data.json)
A bonus test is included.
There are some exercises where we can consider giving the user some practice with the [`options`](https://nim-lang.github.io/Nim/options.html) module, but I don't think `largest-series-product` is a good first candidate.
The example solution can be much shorter, but this is one exercise where it might interest the user to write a more efficient solution. This commit's `example.nim` uses at most:
- one multiplication per input digit
- one integer division per slice
and takes advantage of zeros.
One …
=> Implement exercise: largest-series-product

config.json, exercises/luhn/README.md, exercises/luhn/example.nim, exercises/luhn/luhn_test.nim
[Exercise description](https://github.com/exercism/problem-specifications/blob/master/exercises/luhn/description.md)
[Canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/luhn/canonical-data.json)
The example solution creates a lookup at compile-time for the "double or double minus 9" rule, and uses only one loop over the input.
Some exercises such as `pascals-triangle` (`luhn` isn't the best example) can be substantially "solved" at compile-time in Nim. Since this is an interesting and accessible feature, we could consider adding a `topic` or `hint.md` to those exercises to indicate a bonus task.
=> Implement exercise: luhn

config.json, exercises/meetup/README.md, exercises/meetup/example.nim, exercises/meetup/meetup_test.nim
[Exercise description](https://github.com/exercism/problem-specifications/blob/master/exercises/meetup/description.md)
[Canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/meetup/canonical-data.json)
- The return type is a `string`, not `DateTime` or `int`.
- The weekday parameter is of type `Weekday`, not `string`.
- For good Nim style, the parameters should be ordered to best support method-call syntax. But I just use the upstream order of `2015.meetup(2, Last, dSun)` - I'm not convinced that something like `dSun.meetup(Last, 2015, 2)` is sufficiently improved.
- As a style convention, I use `func` when possible. In this exercise, `proc` is necessary because side-effects are introduced by `times`.
- This exercise shouldn't be the first to use …
=> Implement exercise: meetup

config.json, exercises/pascals-triangle/README.md, exercises/pascals-triangle/example.nim, exercises/pascals-triangle/pascals_triangle_test.nim
[Exercise description](https://github.com/exercism/problem-specifications/blob/master/exercises/pascals-triangle/description.md)
[Canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/pascals-triangle/canonical-data.json)
This is a good exercise for compile-time computation. We could add a `hints.md` file to such exercises, or add a `topic` in `config.json` to suggest it as a bonus task.
In the example solution I generate 30 rows just so that the maximum integer produced won't overflow on 32-bit architectures.
=> Implement exercise: pascals-triangle

config.json, exercises/perfect-numbers/README.md, exercises/perfect-numbers/example.nim, exercises/perfect-numbers/perfect_numbers_test.nim
[Exercise description](https://github.com/exercism/problem-specifications/blob/master/exercises/perfect-numbers/description.md)
[Canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/perfect-numbers/canonical-data.json)
This exercise is a reasonable candidate if we ever want to give users some practice with the [options module](https://nim-lang.github.io/Nim/options.html). One language that uses an `Option` for `perfect-numbers` is [Rust](https://github.com/exercism/rust/blob/master/exercises/perfect-numbers/example.rs).
There seems to be no upstream convention for capitalization of test names. The majority are lowercase, so I lowercase them all for consistency.
=> Implement exercise: perfect-numbers

config.json, exercises/protein-translation/README.md, exercises/protein-translation/example.nim, exercises/protein-translation/protein_translation_test.nim
[Exercise description](https://github.com/exercism/problem-specifications/blob/master/exercises/protein-translation/description.md)
[Canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/protein-translation/canonical-data.json)
The return type is `seq[string]`, not a `seq` of some amino acid `enum`. An `enum` implementation would cover the same ground as other `enum` exercises, and any such amino acid `enum` should contain all the canonical amino acids, rather than just the ones used for this exercise. I looked at some other tracks and didn't see one that used an `enum`.
The tests do not require the example solution's `raise` statements.
=> Implement exercise: protein-translation

config.json, exercises/resistor-color/README.md, exercises/resistor-color/example.nim, exercises/resistor-color/resistor_color_test.nim
[Exercise description](https://github.com/exercism/problem-specifications/blob/master/exercises/resistor-color/description.md)
[Canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/resistor-color/canonical-data.json)
The return type of `colors` is `array`, not `seq`.
However, a `seq` implementation will also pass the tests as e.g. `@[1, 2] == [1, 2]` is `true`.
=> Implement exercise: resistor-color

config.json, exercises/say/README.md, exercises/say/example.nim, exercises/say/say_test.nim
[Exercise description](https://github.com/exercism/problem-specifications/blob/master/exercises/say/description.md)
[Canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/say/canonical-data.json)
The example solution uses a forward declaration for `say`.
`int64` is used.
Some tracks extend this exercise by spelling out the number with "and".
=> Implement exercise: say

config.json, exercises/spiral-matrix/README.md, exercises/spiral-matrix/example.nim, exercises/spiral-matrix/spiral_matrix_test.nim
[Exercise description](https://github.com/exercism/problem-specifications/blob/master/exercises/spiral-matrix/description.md)
[Canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/spiral-matrix/canonical-data.json)
The matrix is always square, so a return type of `array[n, array[n, int]]` makes sense. It also reduces overlap with other nested `seq` exercises and gives users some practice with `static[T]`.
A `seq[array[n, int]]` implementation will also pass the tests, but `seq[seq[int]]` won't.
This exercise should be placed after exercises `matrix` and `saddle-points`.
We can consider adding a `hints.md` file to the first exercise on the track that uses `static[T]`.
=> Implement exercise: spiral-matrix

config.json, exercises/sublist/README.md, exercises/sublist/example.nim, exercises/sublist/sublist_test.nim
[Exercise description](https://github.com/exercism/problem-specifications/blob/master/exercises/sublist/description.md)
[Canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/sublist/canonical-data.json)
The input types are implemented as `array`, not `seq`. This pushes the user to use `openArray`, which is the correct type for functions that work with both `array` and `seq`. I think this is an important detail that this exercise can reinforce, rather than relying on mentors to suggest changes to every `sublist(a, b: seq[int])` implementation. Maybe we can pick an earlier exercise where that happens.
Nim defines `[1, 2] == @[1, 2]` as `true`, so it makes sense insist that `[1, 2].sublist(@[1, 2])` is possible (and returns `Equal`). Using `array` does …
=> Implement exercise: sublist

config.json, exercises/crypto-square/README.md, exercises/crypto-square/crypto_square_test.nim, exercises/crypto-square/example.nim
[Exercise description](https://github.com/exercism/problem-specifications/blob/master/exercises/crypto-square/description.md)
[Canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/crypto-square/canonical-data.json)
Here's how various popular tracks name the function:
| Language | Function name     |
| -------- | ----------------- |
| F#       | `ciphertext`      |
| C#       | `ciphertext`      |
| Python   | `encode`          |
| Go       | `encode`          |
| Java     | `getCipherText`   |
| Haskell  | `encode`          |
| Elixir   | `encode`          |
| Ruby     | `ciphertext`      |
| Rust     | `encrypt`         |
I lean towards `encrypt`. It doesn't distinguish this function from the ones in other cryptography exercises, but neither do the …
=> Implement exercise: crypto-square

config.json, exercises/diamond/README.md, exercises/diamond/diamond_test.nim, exercises/diamond/example.nim
[Exercise description](https://github.com/exercism/problem-specifications/blob/master/exercises/diamond/description.md)
[Canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/diamond/canonical-data.json)
This is another exercise where a lookup can be computed at compile-time.
Some tracks (e.g. C#, F#, Go) do not use the `canonical-data` for this exercise and instead use their own property-based tests.
The upstream exercise description arguably implies that the return type is `string`. Nevertheless, some prominent tracks do use a `seq[string]`-like data structure, which means that the user doesn't have to think about newlines in a final `string` representation.
I think that `seq[string]` is more elegant, but it reduces the range of possible solutions. …
=> Implement exercise: diamond

config.json, exercises/diffie-hellman/README.md, exercises/diffie-hellman/diffie_hellman_test.nim, exercises/diffie-hellman/example.nim
[Exercise description](https://github.com/exercism/problem-specifications/blob/master/exercises/diffie-hellman/description.md)
[Canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/diffie-hellman/canonical-data.json)
Most tracks that implement this exercise either have built-in bigints, or are using a bigint library. Nim does not have bigints in the stdlib, and I don't think we should start using Nimble packages yet.
Unless I'm missing something, the lack of bigints presents an issue with the final `canonical-data` test. The [`p = 23`](https://github.com/exercism/problem-specifications/blob/51418ec78bcca075b586d4c38d66d2c322b488fe/exercises/diffie-hellman/canonical-data.json#L60) produces an overflow about 30% of the time when:
- The integer type stores …
=> Implement exercise: diffie-hellman

config.json, exercises/phone-number/README.md, exercises/phone-number/example.nim, exercises/phone-number/phone_number_test.nim
[Exercise description](https://github.com/exercism/problem-specifications/blob/master/exercises/phone-number/description.md)
[Canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/phone-number/canonical-data.json)
This exercise is another candidate if we ever want to give users some practice with the [options](https://nim-lang.github.io/Nim/options.html) module. Some tracks (e.g. [Rust](https://github.com/exercism/rust/blob/master/exercises/phone-number/tests/phone-number.rs)) do something similar.
An informal benchmark shows that removing the first character of `result` in-place with 
```Nim
for i in 0 .. 9:
result[i] = result[i+1]
result.setLen(10)
```
makes `clean` run about 10% faster than using
```Nim
result = result[1 .. ^1]
```
=> Implement exercise: phone-number

config.json, exercises/proverb/README.md, exercises/proverb/example.nim, exercises/proverb/proverb_test.nim
[Exercise description](https://github.com/exercism/problem-specifications/blob/master/exercises/proverb/description.md)
[Canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/proverb/canonical-data.json)
The return type is implemented as `string`, not `seq[string]`. This is arguably less elegant (as the user must handle newlines), but it might fit the exercise description better.
=> Implement exercise: proverb

config.json, exercises/resistor-color-duo/README.md, exercises/resistor-color-duo/example.nim, exercises/resistor-color-duo/resistor_color_duo_test.nim
[Exercise description](https://github.com/exercism/problem-specifications/blob/master/exercises/resistor-color-duo/description.md)
[Canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/resistor-color-duo/canonical-data.json)
I implement the input type as `array`, not `seq`. This is because:
- The `value` function is only defined for a container of length 2.
- It seems more important to allow a parameter of type `array[2, ResistorColor]` rather than allowing `seq[ResistorColor]` (a `seq` parameter should almost always be an `openArray` instead). Of course, both allow `openArray[ResistorColor]`.
- It allows the user to practise defining arrays, which is rare on the Nim track and a goal of the resistor exercises.
- Input validation tests were deliberately …
=> Implement exercise: resistor-color-duo

config.json, exercises/robot-name/README.md, exercises/robot-name/example.nim, exercises/robot-name/robot_name_test.nim
[Exercise description](https://github.com/exercism/problem-specifications/blob/master/exercises/robot-name/description.md)
(No canonical data)
This is the first exercise on the Nim track that doesn't have canonical data. The are considerable differences in how other tracks implement it.
The exercise description states
> Your solution must ensure that every existing robot has a unique name.
But out of 28 tracks that implement `robot-name`, only half test for uniqueness. Of these, six test all possible names - they are `go`, `javascript`, `ocaml`, `perl6`, `ruby` and `scala`.
| Track                                                                                    | Tests many names?                                                                                                  | How …
=> Implement exercise: robot-name

config.json, exercises/scale-generator/README.md, exercises/scale-generator/example.nim, exercises/scale-generator/scale_generator_test.nim
[Exercise description](https://github.com/exercism/problem-specifications/blob/master/exercises/scale-generator/description.md)
[Canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/scale-generator/canonical-data.json)
I implement the intervals input type as `string`. One alternative could be `seq[Interval]`, where `Interval` is
```Nim
type Interval = enum
m, M, A
```
The example implementation could be faster by avoiding `find` or `mod`. All the required scales could also be generated at compile-time.
8 other tracks implement `scale-generator`:
- [csharp](https://www.github.com/exercism/csharp/tree/master/exercises/scale-generator)
- [elixir](https://www.github.com/exercism/elixir/tree/master/exercises/scale-generator)
- …
=> Implement exercise: scale-generator

config.json, exercises/twelve-days/README.md, exercises/twelve-days/example.nim, exercises/twelve-days/twelve_days_test.nim
[Exercise description](https://github.com/exercism/problem-specifications/blob/master/exercises/twelve-days/description.md)
[Canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/twelve-days/canonical-data.json)
- Similar exercises are `house` (easier) and `food-chain` (harder). Also somewhat similar: `beer-song`, `diamond`, `proverb`.
- This is another exercise that can be computed at compile-time.
- The tests do not check that the user actually generates every verse. The user can hard-code them.
- There are some very long lines in the test file. However, splitting them over multiple lines doesn't really help, and other tracks do the same.
I implement the return type as `string`, not `seq[string]`. This is less elegant (as the user must handle …
=> Implement exercise: twelve-days

config.json, exercises/yacht/README.md, exercises/yacht/example.nim, exercises/yacht/yacht_test.nim
[Exercise description](https://github.com/exercism/problem-specifications/blob/master/exercises/yacht/description.md)
[Canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/yacht/canonical-data.json)
This is a good exercise to practice using modules like `algorithm`, `sequtils`, `tables`, and `sets`. The user may also find it interesting to benchmark different approaches.
For this exercise I think it's worth having a faster example implementation at the cost of brevity, but we don't need the code for computing a lookup at compile-time.
I implement the input type as
```Nim
test "two pair is not a Full House":
check score([2, 2, 4, 4, 5], FullHouse) == 0
```
not
```Nim
test "two pair is not a Full House":
check score([Two, Two, Four, Four, Five], …
```
=> Implement exercise: yacht

exercises/allergies/allergies_test.nim, exercises/anagram/README.md, exercises/anagram/anagram_test.nim, exercises/bob/README.md, exercises/darts/README.md, exercises/darts/darts_test.nim, exercises/etl/etl_test.nim, exercises/leap/leap_test.nim, exercises/luhn/luhn_test.nim, exercises/pangram/pangram_test.nim, exercises/queen-attack/queen_attack_test.nim, exercises/reverse-string/reverse_string_test.nim, exercises/triangle/triangle_test.nim, exercises/two-fer/README.md, exercises/word-count/README.md
(Do not squash).
This PR brings the track up-to-date by updating tests and READMEs.
I use only one PR here because:
- The commits have the same purpose (apart from two minor refactorings).
- It allows the updates to be merged in chronological order (by date of upstream change).
- It helps the refactorings to be merged before the updates.
- Travis only needs to run once.
- Most of the changes are trivial.
The updates to tests in this PR correspond to the following upstream changes:
| Exercise       |                                                                                                                                                   | …
=> Update tests and READMEs

exercises/isogram/example.nim, exercises/pangram/example.nim, exercises/react/example.nim, exercises/robot-name/robot_name_test.nim, exercises/roman-numerals/example.nim, exercises/scale-generator/example.nim
This PR fixes warnings in the current (and upcoming) version of `check_exercises.nim`. It fixes:
- All deprecation warnings (see [recent Travis log](https://travis-ci.org/exercism/nim/builds/568761380#L1285) and [Nim `sets` docs](https://nim-lang.org/docs/sets.html#initSet)).
- All `styleCheck:hint` warnings.
=> Fix deprecation warnings and styleCheck warnings

exercises/acronym/example.nim, exercises/anagram/example.nim, exercises/binary/example.nim, exercises/leap/example.nim, exercises/matrix/example.nim, exercises/meetup/example.nim, exercises/nth-prime/example.nim
This PR addresses these small problems shown by `devel` Nim:
- Unused imports
- Newer `styleCheck` suggestions (overlooked in #209)
It also removes the (now-default) `procvar` pragmas. This change is relevant because one of them is capitalized as `procVar`, which produces a `styleCheck` hint.
=> Remove unused imports; Apply styleCheck suggestions

README.md, _test/check_exercises.nim, exercises/twelve-days/example.nim
This PR rewrites `check_exercises.nim`.
Summary:
- Support stub files.
- Speed up testing of multiple exercises. Testing all exercises is about 7x faster on my machine, and Travis CI builds now take 40–60 seconds, not 2.5–3.5 minutes.
- Add some features that are convenient during development (e.g. `--quiet` mode and abbreviated exercise name arguments).
- Workaround a compiler bug that is triggered by the `twelve-days` example.
See the commit messages for further details.
=> CI(check_exercises): Support stubs; speed up; improve convenience

config.json, exercises/resistor-color-trio/README.md, exercises/resistor-color-trio/example.nim, exercises/resistor-color-trio/resistor_color_trio_test.nim
[Exercise description](https://github.com/exercism/problem-specifications/blob/master/exercises/resistor-color-trio/description.md)
[Canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/resistor-color-trio/canonical-data.json)
- Implement the input type as an `array`, not a `seq`.
- Support only `tuple` (and not `object`) as the return type.
- `example.nim`: Support megaohms and gigaohms.
- `example.nim`: Omit creating a compile-time lookup.
4 other tracks implement `resistor-color-trio`:
- [bash](https://www.github.com/exercism/bash/tree/master/exercises/resistor-color-trio)
- [c](https://www.github.com/exercism/c/tree/master/exercises/resistor-color-trio)
- [javascript](https://www.github.com/exercism/javascript/tree/master/exercises/resistor-color-tri …
=> Feature(resistor-color-trio): Implement exercise

.travis.yml
This PR updates the Travis CI configuration to use the latest Nim release.
See [changelog](https://github.com/nim-lang/Nim/blob/devel/changelogs/changelog_1_0_2.md).
=> CI(Travis): Use Nim 1.0.2

.travis.yml
This PR updates the Travis CI configuration to use the latest Nim release.
See https://nim-lang.org/blog/2019/11/26/version-104-released.html
=> CI(Travis): Use Nim 1.0.4

_test/check_exercises.nim, exercises/robot-name/example.nim, exercises/robot-name/robot_name_test.nim
This PR:
- Removes the "unused import" warning that appeared in CI logs.
- Enables the `robot-name` bonus test during CI.
- Better optimizes the `robot-name` example implementation and its bonus test.
See the commit messages for more details.
=> robot-name: Fix warning; Enable bonus test for CI

bin/fetch-configlet
This PR makes the `fetch-configlet` script more robust and idiomatic.
Upstream: https://github.com/exercism/configlet/blob/master/scripts/fetch-configlet
=> CI: Update `fetch-configlet` script

.github/workflows/configlet.yml, bin/fetch-configlet
CI builds would sometimes fail when downloading `configlet`, seemingly due to rate-limiting. This commit adds authentication to raise that limit.
Upstream: https://github.com/exercism/configlet/commit/c70be62
=> CI(fetch-configlet): Add authentication

exercises/queen-attack/example.nim, exercises/queen-attack/queen_attack_test.nim
Previously, we did not implement the first test case of the canonical data:
```json
{
"uuid": "3ac4f735-d36c-44c4-a3e2-316f79704203",
"description": "queen with a valid position",
"property": "create",
"input": {
"queen": {
"position": {
"row": 2,
"column": 2
}
}
},
"expected": 0
},
```
This PR:
- Reimplements the exercise from the canonical data so that we can add
the missing test case, which will allow us to set all the tests to
`true` in `queen-attack/.meta/tests.toml`.
- Changes the `canAttack` and `board` procs to take a `Queen` object as
their argument, rather than a pair of (row, col) tuples. This is more
in the spirit of the canonical data. It also allows us to remove the
bonus checking of invalid positions in `board`.
- Changes the `board` proc to return a `string` rather than a …
=> Refactor(queen-attack): Reimplement exercise

exercises/perfect-numbers/README.md, exercises/perfect-numbers/perfect_numbers_test.nim
I already made the substitution "natural" -> "positive" when I implemented this exercise, to avoid potential confusion with the
`Natural` type in `system` (see [system.Natural](https://nim-lang.github.io/Nim/system.html#Natural)), which is defined as:
```Nim
Natural = range[0 .. high(int)]
```
Upstream: https://github.com/exercism/problem-specifications/commit/fcbc25191f44
=> Refactor(perfect-numbers): Prefer "positive integers"

exercises/darts/README.md
All the other exercise `README.md` files contain this empty line.
Upstream: https://github.com/exercism/problem-specifications/commit/381c30e469a8
=> README(darts): Add empty line before header

.github/workflows/configlet.yml
The CI check for `configlet generate` should fail until https://github.com/exercism/nim/pull/257 is merged.
To-do:
=> CI(configlet): use GitHub Action to install configlet; add `configlet generate`

.github/workflows/exercises.yml, .travis.yml
This PR adds a workflow that runs `check_exercises.nim` on:
- Linux, with Nim stable (currently 1.4.0)
- Linux, with Nim devel
- macOS, with Nim stable
and removes those jobs from the Travis CI configuration.
For now, this PR keeps the Travis jobs that run on `arm64` and `ppc64le`.
This gets most of the way to resolving https://github.com/exercism/nim/issues/251.
I intend to make separate PRs later that:
- compile with `--styleCheck:error`, not `--styleCheck:hint`
- add Windows
- remove Travis completely
=> CI: Move amd64 `check_exercises` jobs to GitHub Actions

.github/workflows/uuids.yml, _test/check_uuids.nim
This PR adds UUID-checking to CI. 
It adds `_test/check_uuids.nim`, which checks that every UUID in the track `config.json` file:
- is a valid version 4 UUID in the lowercase and hyphen-separated form
- is unique within the track
- does not exist on another Exercism track
- does not exist in the `exercism/problem-specifications` repo
Otherwise, it prints the bad UUID(s) and quits with a non-zero exit code.
Sample output: https://github.com/exercism/nim/runs/1649727754#step:9:92
```
Downloading 1/75: 05ab1e
Downloading 2/75: ada
[...]
Downloading 74/75: vimscript
Downloading 75/75: x86-64-assembly
3267 distinct UUIDs on tracks other than 'exercism/nim'.
Cloning exercism/problem-specifications...
1694 distinct UUIDs in 'exercism/problem-specifications'.
68 distinct UUIDs on the nim track. …
```
=> CI: Check UUIDs are valid and unique across Exercism

README.md
We already transitioned from Travis CI to GitHub Actions.
=> docs(README): remove references to Travis CI

config.json
This deliberately omits some tags that we could conceivably add, such as:
- `paradigm/functional`
- `paradigm/object_oriented`
- `execution_mode/interpreted`
- `platform/ios`
- `platform/android`
- `runtime/language_specific`
The spec currently contains:
> Tracks can be annotated with tags, which allows searching for tracks
> with a certain tag combination.
> A track should choose their tags based on the general usage of their
> language. For example, imagine a student thinking: "I'd like to do
> machine learning, what language should I pick?", or "I'd like to learn
> functional programming, which language should I choose?". If your
> language would be a good candidate, give it that tag. If your language
> supports some functional ideas but they're rarely used, or a few
> people do …
=> config.json: populate `tags`

.appends/.github/labels.yml
This PR adds a `.appends/.github/labels.yml` file, which contains
every label that is currently present in this repo. A future
`.github/labels.yml` file will contain the full list of labels that this
repo can use, which will be a combination of the
`.appends/.github/labels.yml` file and a centrally-managed `labels.yml`
file.
We'll automatically sync any changes, which allows us to guarantee that
every track repository will have a pre-determined set of labels,
augmented with any custom, repo-specific labels in the
`.appends/.github/labels.yml` file.
https://github.com/exercism/v3-launch/issues/41
=> 🤖 labels: add initial `.appends` file

_test/check_exercises.nim
I'm not sure the order of event for reviewing/merging for this and #339. Without the changes in #339 this fails because `test_lasagna.nim` is empty so the text wrangling that is done doesn't work properly.
This also includes 2 small refactors:
1. e576d23 switches to `toSeq` instead of assigning to a `var seq` for readability and immutability enforcement
2. eedf7a0 removes the deprecated `TaintedString` `distinct string` type
=> CI: Add concept exercies to ci

.github/workflows/exercises.yml
GitHub dropped macOS-12 support. Workflow needs updating to 14.
See: https://forum.exercism.org/t/github-actions-runner-breaking-changes-announced/12612
=> fix: update macOs workflow
